// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview Generates a unique digital fingerprint for an object from an image.
 *
 * - generateObjectFingerprint - A function that generates the object fingerprint.
 * - GenerateObjectFingerprintInput - The input type for the generateObjectFingerprint function.
 * - GenerateObjectFingerprintOutput - The return type for the generateObjectFingerprint function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';
import {scanObject} from '@/services/object-scanner';

const GenerateObjectFingerprintInputSchema = z.object({
  imageBase64: z.string().describe('The base64 encoded image of the object.'),
});
export type GenerateObjectFingerprintInput = z.infer<
  typeof GenerateObjectFingerprintInputSchema
>;

const GenerateObjectFingerprintOutputSchema = z.object({
  fingerprint: z.string().describe('The unique digital fingerprint of the object.'),
});
export type GenerateObjectFingerprintOutput = z.infer<
  typeof GenerateObjectFingerprintOutputSchema
>;

export async function generateObjectFingerprint(
  input: GenerateObjectFingerprintInput
): Promise<GenerateObjectFingerprintOutput> {
  return generateObjectFingerprintFlow(input);
}

const generateObjectFingerprintFlow = ai.defineFlow<
  typeof GenerateObjectFingerprintInputSchema,
  typeof GenerateObjectFingerprintOutputSchema
>(
  {
    name: 'generateObjectFingerprintFlow',
    inputSchema: GenerateObjectFingerprintInputSchema,
    outputSchema: GenerateObjectFingerprintOutputSchema,
  },
  async input => {
    const scanResult = await scanObject(input.imageBase64);
    return {fingerprint: scanResult.fingerprint};
  }
);
